contact_links:
  - name: Повідомити про баг
    url: https://github.com/space-wizards/space-station-14/issues/new/choose
    about: Посилання на створення повідомлення про помилку в офіційному репозиторії SS14.
